server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_sms?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123568
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

#静态资源配置
resources:
  static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.niit.sms.bean

logging:
  level:
    com:
      example:
        mapper: debug
